name: syngeny-env
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - pyyaml
  - requests
  - tqdm
  - matplotlib
  - ipykernel
  - pip:
      - torch
      - transformers
      - datasets
      - huggingface_hub
      - safetensors
      - tokenizers
      - openai
